language: php
php:
  - 5.2
  - 5.3
  - 5.4
matrix:
  allow_failures:
    - php: 5.2
branches:
  not:
    - master
before_script:
  - mysql -e 'create database blackhawk;'
script:
  - if [ 'php' != '5.2' ]; then phpunit --configuration phpunit.xml --coverage-text; fi
  - if [ 'php' = '5.2' ]; then phpunit --configuration phpunit.xml; fi