language: php
php:
  - 5.2
  - 5.3
  - 5.4
before_script:
  - mysql -e 'create database blackhawk;'
script: phpunit --configuration phpunit.xml --coverage-text --coverage-clover "clover"
notifications:
  email:
    - chriscct7@gmail.com 
