<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-27 at 01:32:34.
 */
class noticeTest extends PHPUnit_Framework_TestCase {

    /**
     * @var notice
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new notice;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers notice::add
     * @todo   Implement testAdd().
     */
    public function testAdd() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers notice::report
     * @todo   Implement testReport().
     */
    public function testReport() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers notice::errorsExist
     * @todo   Implement testErrorsExist().
     */
    public function testErrorsExist() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
