<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-27 at 01:32:33.
 */
class UPDTest extends PHPUnit_Framework_TestCase {

    /**
     * @var UPD
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new UPD;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
